spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      url: jdbc:mariadb://13.124.252.81:3306/teamA
      username: kang
      password: 0629
      driver-class-name: org.mariadb.jdbc.Driver
---
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
---
server:
  port: 8080
